GRANT ALL PRIVILEGES ON *.* TO 'dba'@'localhost' IDENTIFIED BY 'demo_password' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'dba'@'%' IDENTIFIED BY 'demo_password' WITH GRANT OPTION;

FLUSH PRIVILEGES;
